### ISSUE TITLE
SmartScreen!

### ISSUE THREAD

**Issue by 0x4248** [torchgm/ModernWinver#10]
![image](https://user-images.githubusercontent.com/60709927/122739985-73c47f80-d27b-11eb-9fdf-4c21e1a018ba.png)
 I know the app dosen't have a certificate but it was warned as a dangerous app.

**Comment by torchgm** [comment]
Alright? Literally nothing I can do about this. Flag it as not malicious if you want but I can't afford a CSC right now so this will always appear.
