### ISSUE TITLE
[Suggestion] Add Windows 11 support.

### ISSUE THREAD

**Issue by nebula-neru** [torchgm/ModernWinver#11]
ModernWinVer still thinks windows 11 is "windows 10"
It also interprets the build as the last windows 10 dev build instead of 22000
![image](https://user-images.githubusercontent.com/65756037/123894835-ba694800-d913-11eb-9897-af13f90c3508.png)
![image](https://user-images.githubusercontent.com/65756037/123894852-c2c18300-d913-11eb-98dd-f7f7e8964b26.png)

**Comment by torchgm** [comment]
The issue with the build number is because you haven't clicked Refresh (which is also done automatically weekly). As for Windows 11 support, can't say anything definitive yet but:
![image](https://user-images.githubusercontent.com/31840547/123920488-e9b49f00-d97d-11eb-9201-22031ce64042.png)

**Comment by nebula-neru** [comment]
I see, yeah I hadn't launched ModernWinVer in quite a while, thought that was the program. As for the win11 support, it looks really good. Can't wait !!!!
