### ISSUE TITLE
21H1 is identified incorrectly

### ISSUE THREAD

**Issue by rounk-ctrl** [torchgm/ModernWinver#5]
21H1 is identified as 20h2
![image](https://user-images.githubusercontent.com/70931017/112860512-eda5fc00-90c4-11eb-9610-553928db63d4.png)

**Comment by torchgm** [comment]
Can you provide the contents of `%localappdata%/winver.json` please? Either here or in DMs on Discord if you'd prefer to not have it public.

**Comment by rounk-ctrl** [comment]
sure

**Comment by torchgm** [comment]
I'm assuming this is fixed in the latest release, if not reopen this.

**Comment by rounk-ctrl** [comment]
yea it is fixed
