### ISSUE TITLE
Impossible to launch ModernWinver

### ISSUE THREAD

**Issue by NoodleIsFlying** [torchgm/ModernWinver#7]
Whenever I try running ModernWinver, I get an error saying "This application could not be started, do you want to view information about this issue ?" I tried running .NET Framework 3.5 but nothing happened, and the tool to fix NET Framework did not work either.

**Comment by torchgm** [comment]
Hi, can you provide screenshots of the error, the additional information it's asking you if you want to view, and the versions of .NET you currently have available on your system? (You can check with [this tool](https://www.raymond.cc/blog/download/did/1741/))

**Comment by ThatStella7922** [comment]
![image](https://user-images.githubusercontent.com/10524728/121271027-09c1d880-c880-11eb-9694-235441380960.png)
Screenshot of the issue. Clicking 'Yes' opens [this](https://docs.microsoft.com/en-us/dotnet/framework/install/application-not-started?version=(null)&processName=mwinver.exe&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0) page in the default web browser



![image](https://user-images.githubusercontent.com/10524728/121271090-2a8a2e00-c880-11eb-8fa5-6b1eab932d3b.png)
This is what the .NET detector you linked says.

Running Windows 10 x64 20H2 build 19042.985

**Comment by torchgm** [comment]
This issue is a fault with your .NET installation; I'd recommend running the repair tool linked on the page that opens after you click "yes" as this usually resolves the error.

**Comment by ThatStella7922** [comment]
I have already tried that, it churned for a bit, said it “succeeded” and modernwinver still doesn’t run

more details when I get home from work
